Getting Started.md
- Some formatting changes (particularly near the end)
- Some language changes
- Some new linkgs
=> Expand on getting started

Deployment and Next Steps.md, SUMMARY.md
fixes https://github.com/elmbridge/curriculum/issues/12
=> adds afternoon release 6

CODE_OF_CONDUCT.md, README.md
installed by the following command: npm install -g covgen && covgen saviinirs@gmail.com
see: http://contributor-covenant.org/ for more information.
=> Adds the Contributor Convenant

CONTRIBUTING.md, README.md
language is heavily adapted from https://github.com/railsbridge/docs/blob/c82946949947bae66e4f73737371eb3a77c7f2d7/CONTRIBUTING.md
hat tip to @nuclearsandwich for putting this together
=> add contributing guidelines

Getting Started.md, Introduction.md, README.md, SUMMARY.md, book.json
fixes https://github.com/elmbridge/curriculum/issues/2
=> Adds gitbook-specific introduction with installation instructions

Building User Interfaces.md, SUMMARY.md
=> adds morning release 6

The Basic Building Blocks of Elm.md
=> adds section matching `if` assertions in intro-to-elm app

Building User Interfaces.md, Getting Started.md, The Basic Building Blocks of Elm.md, Why Elm.md
A collection of typo fixes for the morning chapters.
=> :art: Fix typos

Choose Your Own Emoji.md, Deployment and Next Steps.md, Emojification.md, Making It Dynamic.md, Our First Full Feature.md, The Elm Architecture.md
Stuff I noticed while reading through:
- The Elm Architecture
- Making It Dynamic
- Emojification!!!
- Our First Full Feature
- Choose Your Own Emoji
- Deployment and Next Steps
=> :art: fix typos in the afternoon chapters

Making It Dynamic.md, Our First Full Feature.md, The Basic Building Blocks of Elm.md, The Elm Architecture.md
plus two commits I meant to push to #62
=> Some more opinionated edits for the afternoon chapters

Deployment and Next Steps.md, Emojification.md, Our First Full Feature.md, The Basic Building Blocks of Elm.md
fixes #69 
fixes #76 
fixes #67 
fixes #54
=> littany of small fixes

Choose Your Own Emoji.md, Making It Dynamic.md, Our First Full Feature.md
in addition to new feature, fixes https://github.com/elmbridge/curriculum/issues/66
=> add more detail to union types and tagged values

The Elm Architecture.md
fixes #70 (copy from https://github.com/elmbridge/curriculum/issues/70#issuecomment-254361133)
merging because I've mostly just adapted @ento's words.
=> add explanation for model 'changing'

Choose Your Own Emoji.md, Our First Full Feature.md
things I noticed while reading #81
=> :art: fix typos around union types

Emojification.md
For https://github.com/elmbridge/curriculum/issues/87
=> Add info about secret decoder rings

Deployment and Next Steps.md, Emojification.md, Making It Dynamic.md, Our First Full Feature.md, The Elm Architecture.md
This updates the curriculum content to match the change to use elm-reactor in the afternoon project.  See https://github.com/elmbridge/elmoji-translator/issues/3
=> Use elm-reactor in the afternoon

Getting Started.md, Introduction.md, Our First Full Feature.md, The Elm Architecture.md
@avh4 @tesk9 @raorao 
I took some time to review curriculum.
1. Amazing. Love the app. Great descriptions. Nicely done!
2. I've added a couple things that address some questions that I thought I would have if I was a student. git commits are very descriptive and are 1 change at a time, so it should be reasonable to review.
<3
=> Strickinato changes

Emojification.md, Our First Full Feature.md, The Elm Architecture.md
=> Minor proofreading edits

Introduction.md, SUMMARY.md, Special Installation Notes.md
- Proposes solution to observations in #100
=> Checklist to help Windows users

Making It Dynamic.md, The Elm Architecture.md
=> switch to 0.18 for emoji translator

Why Elm.md
Attempt at resolving https://github.com/elmbridge/curriculum/issues/35
- separates out the Why & Why Not sections explicitly
- weaves the "rules" idea through the what-is-this section
=> Draft new version

Making It Dynamic.md, Our First Full Feature.md, The Basic Building Blocks of Elm.md, The Elm Architecture.md
here are a bunch of small changes discovered when running through the curriculum.
great work! This is such a nice project!
=> Small fixes

Getting Started.md, Introduction.md, Special Installation Notes.md
Update Elmbridge to the latest version of Elm, I also opened PRs to update elm.json of the exercises
* https://github.com/elmbridge/elmoji-translator/pull/11
* https://github.com/elmbridge/elm-basics/pull/14
=> Update to Elm 0.19.1

Choose Your Own Emoji.md, Getting Started.md, Introduction.md, Our First Full Feature.md, The Basic Building Blocks of Elm.md, The Elm Architecture.md
This fixes a few things that we noticed at the recent [ElmBridge Berlin](https://www.bridgetroll.org/events/537)
* updated the links
* updated the type signature of `Browser.sandbox`
* fixed the syntax of the `if` statement
=> Some fixes to the curriculum
